### ISSUE TITLE
Configure line height for editors

### ISSUE THREAD

**Issue by ctron** [eclipse-platform/eclipse.platform.text#98] opened 2022-10-06 08:05 UTC
It seems like I am unable to configure a line height for the source code editors.

I know it is a personal preference of me, but I actually do like the option that IntelliJ gives me, to use a line height of 1.2.

**Comment by max6cn** [comment] 2022-11-30 07:24
I believe this bug is duplicate of  bug [26765]( https://bugs.eclipse.org/bugs/show_bug.cgi?id=26765) .
Was following that bug many years ago, I have something that  partially works and hope someone can help me to finish a first PR.

**Closed** 2022-12-01 19:35 UTC
Labels: enhancement

**Comment by lshanmug** [comment] 2023-03-02 17:11
@max6cn Can you pls add a new and noteworthy entry for this so that users can learn about the new preference?

News page for platform - https://www.eclipse.org/eclipse/news/4.27/platform.php
Repo for news content - https://github.com/eclipse-platform/www.eclipse.org-eclipse-news
